### ISSUE TITLE
Recheck

### ISSUE THREAD

**Issue by swarupsro** [lbarman/kali-tools#4]
Currently the program is not working !

**Comment by lbarman** [comment]
Hi, thanks for your feedback. Could you provide more details please ?Are you using python2 or 3 ? it is working on my end.

**Comment by swarupsro** [comment]
i m using ubuntu 16.04.3 LTS !
![screenshot from 2017-11-11 03-07-58](https://user-images.githubusercontent.com/7780919/32678692-900786ae-c68d-11e7-8ed7-25fa995bd89b.png)

**Comment by lbarman** [comment]
It seems that you're unlucky: https://stackoverflow.com/questions/38447738/beautifulsoup-html5lib-module-object-has-no-attribute-base

Would you mind copy/pasting the version of `beautifulsoup4` and `html5lib` that you use ? Via `pip show html5lib`. I confirm it works with `html5lib` version `0.9999999` (7 nines), do you mind downgrading ? Otherwise you'll have to wait for a fix for `html5lib` (for which I'm not responsible for)

**Comment by swarupsro** [comment]
Thanks Problem Solved !
